version: '3.8'

services:
  api:
    build: ./api
    container_name: jobtool_api
    restart: unless-stopped
    volumes:
      - ./api/data:/app/data
    ports:
      - "4000:4000"

  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: jobtool_web
    depends_on:
      - api
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
